apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-break-glass
  labels:
    app: hello-world-break-glass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-break-glass
  template:
    metadata:
      labels:
        app: hello-world-break-glass
      annotations:
        alpha.image-policy.k8s.io/break-glass: "true"
    spec:
      containers:
      - name: hello-world-break-glass
        image: us.gcr.io/wings-verbanicm/hello-world
        ports:
        - containerPort: 80